// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_RHncOa-vdEZyoh74qZ8OWNBPVmY5_w',
    appId: '1:635772142663:web:a340c00b438fcd23b51d62',
    messagingSenderId: '635772142663',
    projectId: 'bryfinance-97400',
    authDomain: 'bryfinance-97400.firebaseapp.com',
    storageBucket: 'bryfinance-97400.appspot.com',
    measurementId: 'G-VEWSJL4XJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4lJ6iCoeioyHYnmak-nI2MAkqIY1zNrg',
    appId: '1:635772142663:android:d8760e6ff5ee5cbfb51d62',
    messagingSenderId: '635772142663',
    projectId: 'bryfinance-97400',
    storageBucket: 'bryfinance-97400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwoxw0aZdn21yP98a36XLguTkurSKHV8',
    appId: '1:635772142663:ios:31bf6fee026ea708b51d62',
    messagingSenderId: '635772142663',
    projectId: 'bryfinance-97400',
    storageBucket: 'bryfinance-97400.appspot.com',
    iosBundleId: 'com.example.bryfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwoxw0aZdn21yP98a36XLguTkurSKHV8',
    appId: '1:635772142663:ios:31bf6fee026ea708b51d62',
    messagingSenderId: '635772142663',
    projectId: 'bryfinance-97400',
    storageBucket: 'bryfinance-97400.appspot.com',
    iosBundleId: 'com.example.bryfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_RHncOa-vdEZyoh74qZ8OWNBPVmY5_w',
    appId: '1:635772142663:web:42c33e01ee708433b51d62',
    messagingSenderId: '635772142663',
    projectId: 'bryfinance-97400',
    authDomain: 'bryfinance-97400.firebaseapp.com',
    storageBucket: 'bryfinance-97400.appspot.com',
    measurementId: 'G-JJC8LZPZ97',
  );
}
